get and list transfer status transition added
hyperwallet/python-sdk pull request #41
Opened 2020-11-16 14:05 UTC by madhankumar3103

get and list transfer status transition added

2020-11-16 17:36 UTC, arao6 requested changes
Pls correct the build errors (lint errors)

2020-11-16 18:35 UTC, vkorotchenko approved these changes

2020-11-17 19:12 UTC, Rrathinasabapath approved these changes
I approve the changes. The changes are ready to be reviewed by others.

2020-11-17 21:05 UTC, arao6 approved these changes

2020-11-17 21:06 UTC, arao6 approved these changes

2020-11-17 21:10 UTC, merged