added filters
hyperwallet/python-sdk pull request #43
Opened 2020-11-16 20:19 UTC by madhankumar3103

added filters

2020-11-16 22:24 UTC, arao6 requested changes
Please fix the build errors

2020-11-18 18:04 UTC, arao6 approved these changes

2020-11-18 19:27 UTC, vkorotchenko approved these changes

2020-11-18 19:41 UTC, merged

2020-11-19 03:51 UTC, Rrathinasabapath reviewed
Please update the comments as suggested.

2020-11-19 03:51 UTC, Rrathinasabapath commented on hyperwallet/models.py
> +    filters_array = {'clientUserId', 'email', 'programToken', 'status', 'verificationStatus'}
Update the comment from dictionary to set. This is a set in Python. Not an array or dictionary. Do for all the similar comments